# Generated by Django 5.2 on 2025-05-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerservice',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
