# Generated by Django 5.2 on 2025-05-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='freelancing_category',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('writing', 'Writing'), ('marketing', 'Marketing'), ('consulting', 'Consulting'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('mechanic', 'Mechanic'), ('painting', 'Painting'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_profile_pics/'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
